# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yh4o65wRp8b9MpAFGUezPtsofUWbMBs
"""

from matplotlib.image import imread
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
import os
from scipy.signal import correlate
from typing import Literal

Img = imread(os.path.join('NFP93_edge%20of%20beam_058 8 Edited.png'))
print(np.shape(Img))
#Gray_Img = np.mean(Img, -1)
Gray_Img = Img
img = plt.imshow(Gray_Img)
img.set_cmap('gray')
plt.axis('off')
plt.show()

def cor_by_size (fig:np.ndarray ,x:int, y:int, axis = Literal[0, 1])->tuple:
  # Dimensions
  d = fig[0:x, 0:y]
  N, M = d.shape

  # Mean and std for normalization
  m = np.mean(d)
  s = np.std(d)
  d_norm = (d - m) / s

  с_all = {
      0:[correlate(row, row, mode='full') / len(row) for row in d_norm],
      1:[correlate(col, col, mode='full') / len(col) for col in d_norm.T]
  }
  c = np.mean(с_all[axis], axis=0)

  lags_c = {
      0:np.arange(-M + 1, M),
      1:np.arange(-N + 1, N)
  }

  c /= np.max(c)
  return (lags_c[axis],c)

lags_c1_0, c1_0 = cor_by_size(Gray_Img,np.shape(Gray_Img)[0],np.shape(Gray_Img)[1], axis=0)
lags_c2_0, c2_0 = cor_by_size(Gray_Img,np.shape(Gray_Img)[0],np.shape(Gray_Img)[1], axis=1)

plt.plot(lags_c1_0, c1_0, color='red', label='X direction')
plt.plot(lags_c2_0, c2_0, color='blue', label='Y direction')
plt.grid(True)
plt.xlabel('Lag')
plt.ylabel('Normalized Autocorrelation Function')
plt.title('Normalized Autocorrelation Functions in Two Directions')
plt.legend()
plt.xlim(-200, 200)
#plt.ylim(-0.2, 0.2)
plt.show()

window_size = 10
epsilon = 0.02

delta_x_1 = np.zeros(window_size)
delta_y_1 = np.zeros(window_size)


sigma_x = np.zeros(window_size)
sigma_y = np.zeros(window_size)


for i in range(window_size):

  scale = i+1 #(0-100)%

  x = round(np.shape(Gray_Img)[0]*scale/100)
  y = round(np.shape(Gray_Img)[0]*scale/100)

  lags_c1, c1 = cor_by_size(Gray_Img,x,y, axis=0)
  lags_c2, c2 = cor_by_size(Gray_Img,x,y, axis=1)

  d_c1=c1_0[lags_c1_0[-1]-lags_c1[-1]:lags_c1_0[-1]+lags_c1[-1]+1]-c1
  d_c2=c2_0[lags_c2_0[-1]-lags_c2[-1]:lags_c2_0[-1]+lags_c2[-1]+1]-c2

  delta_x_1[i] = np.mean(d_c1)
  delta_y_1[i] = np.mean(d_c2)

  sigma_x[i] = np.sqrt(np.sum((d_c1-delta_x_1[i])**2)/np.shape(d_c1)[0])
  sigma_y[i] = np.sqrt(np.sum((d_c2-delta_y_1[i])**2)/np.shape(d_c2)[0])

  sigma_x_smooth = np.convolve(sigma_x, np.ones(window_size)/window_size, mode='valid')
  sigma_y_smooth = np.convolve(sigma_y, np.ones(window_size)/window_size, mode='valid')

while sigma_x_smooth[-1] >= epsilon:

  i+=1
  scale = i+1 #(0-100)%

  x = round(np.shape(Gray_Img)[0]*scale/100)
  y = round(np.shape(Gray_Img)[0]*scale/100)

  lags_c1, c1 = cor_by_size(Gray_Img,x,y, axis=0)
  lags_c2, c2 = cor_by_size(Gray_Img,x,y, axis=1)

  d_c1=c1_0[lags_c1_0[-1]-lags_c1[-1]:lags_c1_0[-1]+lags_c1[-1]+1]-c1
  d_c2=c2_0[lags_c2_0[-1]-lags_c2[-1]:lags_c2_0[-1]+lags_c2[-1]+1]-c2

  delta_x_1 = np.append(delta_x_1,np.mean(d_c1))
  delta_y_1 = np.append(delta_x_1,np.mean(d_c2))

  sigma_x = np.append(sigma_x,np.sqrt(np.sum((d_c1-delta_x_1[i])**2)/np.shape(d_c1)[0]))
  sigma_y = np.append(sigma_y,np.sqrt(np.sum((d_c2-delta_y_1[i])**2)/np.shape(d_c2)[0]))

  sigma_x_smooth = np.convolve(sigma_x, np.ones(window_size)/window_size, mode='valid')
  sigma_y_smooth = np.convolve(sigma_y, np.ones(window_size)/window_size, mode='valid')

x1 = np.linspace(1, i+1, i+1)

x2 = np.linspace(window_size//2+1, i-window_size//2, i-window_size+2)

plt.plot(x1, sigma_x, color='red', label='X direction')
plt.plot(x2, sigma_x_smooth, color='blue', label='X direction')

plt.ylabel('Standard deviation')
plt.xlabel('Scale in percent')
plt.legend()
#plt.ylim(0,0.02)
plt.grid(True)
plt.show()

closest_value = x2[np.abs(sigma_x_smooth - epsilon).argmin()]

scale = closest_value #(0-100)%
x = round(np.shape(Gray_Img)[0]*scale/100)
y = round(np.shape(Gray_Img)[0]*scale/100)

plt.imshow(Gray_Img[0:x, 0:y],cmap='gray')
#plt.set_title(f"{i+1}%")
img.set_cmap('gray')
plt.axis('off')
plt.savefig('resize_NFP93_270325_04 2 Edited.png')
plt.show()
print(x, y, scale)

from matplotlib.image import imread
import matplotlib.pyplot as plt
import numpy as np
from scipy import signal
import os
from scipy.signal import correlate
from typing import Literal

def cor_by_size (fig:np.ndarray ,x:int, y:int, axis = Literal[0, 1])->tuple:
  # Dimensions
  d = fig[0:x, 0:y]
  N, M = d.shape

  # Mean and std for normalization
  m = np.mean(d)
  s = np.std(d)
  d_norm = (d - m) / s

  с_all = {
      0:[correlate(row, row, mode='full') / len(row) for row in d_norm],
      1:[correlate(col, col, mode='full') / len(col) for col in d_norm.T]
  }
  c = np.mean(с_all[axis], axis=0)

  lags_c = {
      0:np.arange(-M + 1, M),
      1:np.arange(-N + 1, N)
  }

  c /= np.max(c)
  return (lags_c[axis],c)

def size_corr (Gray_Img:np.ndarray, window_size = 10, epsilon = 0.02)->tuple:
  #Autocorr_self
  lags_c1_0, c1_0 = cor_by_size(Gray_Img,np.shape(Gray_Img)[0],np.shape(Gray_Img)[1], axis=0)
  lags_c2_0, c2_0 = cor_by_size(Gray_Img,np.shape(Gray_Img)[0],np.shape(Gray_Img)[1], axis=1)

  delta_x_1 = np.zeros(window_size)
  delta_y_1 = np.zeros(window_size)

  sigma_x = np.zeros(window_size)
  sigma_y = np.zeros(window_size)

  for i in range(window_size):

    scale = i+1

    x = round(np.shape(Gray_Img)[0]*scale/100)
    y = round(np.shape(Gray_Img)[0]*scale/100)

    lags_c1, c1 = cor_by_size(Gray_Img,x,y, axis=0)
    lags_c2, c2 = cor_by_size(Gray_Img,x,y, axis=1)

    d_c1=c1_0[lags_c1_0[-1]-lags_c1[-1]:lags_c1_0[-1]+lags_c1[-1]+1]-c1
    d_c2=c2_0[lags_c2_0[-1]-lags_c2[-1]:lags_c2_0[-1]+lags_c2[-1]+1]-c2

    delta_x_1[i] = np.mean(d_c1)
    delta_y_1[i] = np.mean(d_c2)

    sigma_x[i] = np.sqrt(np.sum((d_c1-delta_x_1[i])**2)/np.shape(d_c1)[0])
    sigma_y[i] = np.sqrt(np.sum((d_c2-delta_y_1[i])**2)/np.shape(d_c2)[0])

    sigma_x_smooth = np.convolve(sigma_x, np.ones(window_size)/window_size, mode='valid')
    sigma_y_smooth = np.convolve(sigma_y, np.ones(window_size)/window_size, mode='valid')

  while sigma_x_smooth[-1] >= epsilon:

    i+=1
    scale = i+1

    x = round(np.shape(Gray_Img)[0]*scale/100)
    y = round(np.shape(Gray_Img)[0]*scale/100)

    lags_c1, c1 = cor_by_size(Gray_Img,x,y, axis=0)
    lags_c2, c2 = cor_by_size(Gray_Img,x,y, axis=1)

    d_c1=c1_0[lags_c1_0[-1]-lags_c1[-1]:lags_c1_0[-1]+lags_c1[-1]+1]-c1
    d_c2=c2_0[lags_c2_0[-1]-lags_c2[-1]:lags_c2_0[-1]+lags_c2[-1]+1]-c2

    delta_x_1 = np.append(delta_x_1,np.mean(d_c1))
    delta_y_1 = np.append(delta_x_1,np.mean(d_c2))

    sigma_x = np.append(sigma_x,np.sqrt(np.sum((d_c1-delta_x_1[i])**2)/np.shape(d_c1)[0]))
    sigma_y = np.append(sigma_y,np.sqrt(np.sum((d_c2-delta_y_1[i])**2)/np.shape(d_c2)[0]))

    sigma_x_smooth = np.convolve(sigma_x, np.ones(window_size)/window_size, mode='valid')
    sigma_y_smooth = np.convolve(sigma_y, np.ones(window_size)/window_size, mode='valid')

  x2 = np.linspace(window_size//2+1, i-window_size//2, i-window_size+2)
  closest_value = x2[np.abs(sigma_x_smooth - epsilon).argmin()]
  scale = closest_value

  x = round(np.shape(Gray_Img)[0]*scale/100)
  y = round(np.shape(Gray_Img)[0]*scale/100)
  return (x,y)

x,y = size_corr(Gray_Img,epsilon=0.02)

plt.imshow(Gray_Img[0:x, 0:y],cmap='gray')
#plt.set_title(f"{i+1}%")
img.set_cmap('gray')
plt.axis('off')
plt.savefig('resize_NFP93_270325_04 2 Edited.png')
plt.show()
print(x, y)

Img_1 = imread(os.path.join('NFP93_edge%20of%20beam_058 8 Edited_1.png'))

x,y = size_corr(Img_1,epsilon=0.02)

plt.imshow(Img_1[0:x, 0:y],cmap='gray')
#plt.set_title(f"{i+1}%")
img.set_cmap('gray')
plt.axis('off')
plt.savefig('resize_NFP93_270325_04 2 Edited.png')
plt.show()
print(x, y)

Img_2 = imread(os.path.join('NFP93_edge%20of%20beam_058 8 Edited_2.png'))
Gray_Img_2 = np.mean(Img_2, -1)

x,y = size_corr(Gray_Img_2,epsilon=0.02)

plt.imshow(Img_2[0:x, 0:y],cmap='gray')
#plt.set_title(f"{i+1}%")
img.set_cmap('gray')
plt.axis('off')
plt.savefig('resize_NFP93_270325_04 2 Edited.png')
plt.show()
print(x, y)