# -*- coding: utf-8 -*-
"""for article.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_NpsDtTzfBThCPiRDtTeiALYm-8LNwAR
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.preprocessing import MinMaxScaler
import torch
import torch.nn as nn
import torch.optim as optim

df_target = pd.read_csv("Output of all frame.csv")
df_features = pd.read_csv("BGR mean of all frame.csv")

# Оставляем нужные столбцы
y = df_target['Answer'].copy()
X = df_features[['B', 'G', 'R']].copy()
X = X.round(0).astype(int)

X

y

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.hist(y, bins=10, color='skyblue', edgecolor='black')
plt.title("Распределение значений answer")
plt.xlabel("answer")
plt.ylabel("Количество")
plt.grid(True)
plt.show()

# Нормализация target
scaler_y = MinMaxScaler(feature_range=(0, 1))
y_norm_array = scaler_y.fit_transform(y.values.reshape(-1, 1)).round(3).flatten()

# Превращаем обратно в Series с оригинальными индексами
y_norm = pd.Series(y_norm_array, index=y.index, name='answer_norm')

y_norm

plt.figure(figsize=(8, 5))
plt.hist(y_norm, bins=10, color='skyblue', edgecolor='black')
plt.title("Распределение значений answer")
plt.xlabel("answer")
plt.ylabel("Number of samples")
plt.grid(True)
plt.show()

# Создаем бины
bins = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
labels = list(range(len(bins) - 1))
y_bins = pd.cut(y_norm, bins=bins, labels=labels, include_lowest=True)

# Стратифицированное разделение
X_train, X_test, y_train, y_test = train_test_split(
    X, y_norm,
    test_size=0.2,
    stratify=y_bins,
    random_state=42
)

X_train

y_train

# Конвертация в тензоры
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

class FlexibleRegressor(nn.Module):
    def __init__(self, input_size=3, layer_sizes=[64, 32],
                 use_dropout=False, use_batchnorm=False, dropout_p=0.3):
        super(FlexibleRegressor, self).__init__()

        layers = []
        in_features = input_size

        for size in layer_sizes:
            layers.append(nn.Linear(in_features, size))
            if use_batchnorm:
                layers.append(nn.BatchNorm1d(size))
            layers.append(nn.ReLU())
            if use_dropout:
                layers.append(nn.Dropout(p=dropout_p))
            in_features = size

        layers.append(nn.Linear(in_features, 1))  # выходной слой

        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

def train_model(layer_sizes=[64, 32], lr=0.001, epochs=200,
                use_dropout=False, use_batchnorm=False, use_scheduler=False, dropout_p=0.3):

    model = FlexibleRegressor(
        layer_sizes=layer_sizes,
        use_dropout=use_dropout,
        use_batchnorm=use_batchnorm,
        dropout_p=dropout_p
    )

    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5) if use_scheduler else None

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        outputs = model(X_train_tensor)
        loss = criterion(outputs, y_train_tensor)
        loss.backward()
        optimizer.step()
        if scheduler:
            scheduler.step()

    return model

# Оценка
def evaluate(model):
    model.eval()
    with torch.no_grad():
        predictions = model(X_test_tensor).squeeze().numpy()

    y_true = y_test.values

    r2 = r2_score(y_true, predictions)
    mse = mean_squared_error(y_true, predictions)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, predictions)

    print(f"R²:   {r2:.4f}")
    print(f"MSE:  {mse:.4f}")
    print(f"RMSE: {rmse:.4f}")
    print(f"MAE:  {mae:.4f}")
    return r2, mse, rmse, mae

pip install optuna

import optuna

def objective(trial):
    # Подбираем количество слоёв
    num_layers = trial.suggest_int('num_layers', 1, 5)

    # Подбираем размеры каждого слоя индивидуально
    layer_sizes = [
        trial.suggest_categorical(f"layer_{i}_size", [16, 32, 64, 128])
        for i in range(num_layers)
    ]

    # Остальные гиперпараметры
    lr = trial.suggest_float('lr', 1e-4, 1e-2, log=True)
    use_dropout = trial.suggest_categorical('use_dropout', [True, False])
    use_batchnorm = trial.suggest_categorical('use_batchnorm', [True, False])
    use_scheduler = trial.suggest_categorical('use_scheduler', [True, False])
    dropout_p = trial.suggest_categorical('dropout_p', [0.1, 0.2, 0.3, 0.4, 0.5]) if use_dropout else 0.0

    # Инициализация модели
    model = FlexibleRegressor(
        layer_sizes=layer_sizes,
        use_dropout=use_dropout,
        use_batchnorm=use_batchnorm,
        dropout_p=dropout_p
    )

    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5) if use_scheduler else None

    for epoch in range(500):
        model.train()
        optimizer.zero_grad()
        output = model(X_train_tensor)
        loss = criterion(output, y_train_tensor)
        loss.backward()
        optimizer.step()
        if scheduler:
            scheduler.step()

    # Оценка по RMSE
    model.eval()
    with torch.no_grad():
        pred = model(X_test_tensor).squeeze().numpy()
    rmse = np.sqrt(mean_squared_error(y_test.values, pred))
    return rmse

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=1000)

print("\n Best trial:")
trial = study.best_trial
for key, value in trial.params.items():
    print(f"{key}: {value}")

# Обучаем финальную модель с лучшими параметрами
best_params = study.best_trial.params

# Собираем список размеров скрытых слоёв
layer_sizes = [
    best_params[f"layer_{i}_size"] for i in range(best_params['num_layers'])
]
best_model = train_model(
    layer_sizes=layer_sizes,
    use_dropout=best_params['use_dropout'],
    use_batchnorm=best_params['use_batchnorm'],
    use_scheduler=best_params['use_scheduler'],
    dropout_p=best_params['dropout_p'] if best_params['use_dropout'] else 0.0,
    lr=best_params['lr'],
    epochs=500
)

evaluate(best_model)

def assign_class(value):
    if value <= 0.1:
        return 'High aggregation'
    elif value <= 0.5:
        return 'Low aggregation'
    else:
        return 'No aggregation'

best_model.eval()
with torch.no_grad():
    predictions = best_model(X_test_tensor).squeeze().numpy()

predictions = predictions.round(3)

y_true = y_test.values

results_df = pd.DataFrame({
    'R':X_test['R'],
    'G':X_test['B'],
    'B':X_test['B'],
    'Ground Truth': y_true,
    'Prediction': predictions,
    'Abs Error': (y_true - predictions)
})

# Классы
results_df['GT Class'] = results_df['Ground Truth'].apply(assign_class)
results_df['Pred Class'] = results_df['Prediction'].apply(assign_class)

print(results_df.head())

results_df.to_csv("predictions_vs_ground_truth.csv", index=True)